name: bk-devops-case

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
  mern-server:
    build: ./mern-project/server/
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - ATLAS_URI=mongodb://mongodb:27017
    ports:
      - "5050:5050"
  mern-client:
    build: ./mern-project/client/
    restart: unless-stopped
    depends_on:
      - mern-server
    ports:
      - "8000:80"
  python-task:
    build: ./python-project/

volumes:
  db:

networks:
  default:
    name: bk-devops-case-net
