apiVersion: v1
kind: Service
metadata:
  name: mern-client
spec:
  type: ClusterIP
  selector:
    app: mern-client
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.mernClient.port }}
      targetPort: {{ .Values.mernClient.port }}
