apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-client-deployment
spec:
  {{- if not .Values.mernClient.hpa.enabled }}
  replicas: {{ .Values.mernClient.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: mern-client
  template:
    metadata:
      labels:
        app: mern-client
    spec:
      containers:
        - name: mern-client-container
          image: {{ .Values.aws.accountId }}.dkr.ecr.{{ .Values.aws.region }}.amazonaws.com/mern-client:{{ .Values.mernClient.image.tag }}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: {{ .Values.mernClient.resources.requests.cpu }}
              memory: {{ .Values.mernClient.resources.requests.memory }}
            limits:
              cpu: {{ .Values.mernClient.resources.limits.cpu }}
              memory: {{ .Values.mernClient.resources.limits.memory }}
          ports:
            - containerPort: {{ .Values.mernClient.port }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.mernClient.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.mernClient.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
