apiVersion: v2
name: bk-devops-case
version: "1.0.0"
kubeVersion: ">=1.23.0"
description: Helm chart to deploy BK DevOps Case on Kubernetes
type: application
home: https://github.com/emrecankaracayir/bk-devops-case

sources:
  - https://github.com/emrecankaracayir/bk-devops-case

maintainers:
  - name: Emrecan Karaçayır
    email: developer@karacayir.com

appVersion: "1.0.0"
