apiVersion: v1
kind: Service
metadata:
  name: mern-server
spec:
  type: ClusterIP
  selector:
    app: mern-server
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.mernServer.port }}
      targetPort: {{ .Values.mernServer.port }}
